GET http://localhost:8080/week2/contact

###

GET http://localhost:8080/week2/contact/63bc6bedc21a515bbcc0137f

###

GET http://localhost:8080/week2/contact/63bc6bedc21a515bbcc01380

###
GET http://localhost:8080/week2/contact/63bc6bedc21a515bbcc01381



###
GET https://cse341-6rfr.onrender.com/week2/contact

###

GET https://cse341-6rfr.onrender.com/week2/contact/63bc6bedc21a515bbcc0137f

###

GET https://cse341-6rfr.onrender.com/week2/contact/63bc6bedc21a515bbcc01380

###
GET https://cse341-6rfr.onrender.com/week2/contact63bc6bedc21a515bbcc01381





