get http://localhost:8080/week3/contact

###

POST http://localhost:8080/week3/contact/add HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kaya",
    "lastName": "Blomquist",
    "email": "Kaya@gmail.com",
    "favoriteColor": "purple",
    "birthday": "03/12/2021"
}

###

PUT http://localhost:8080/week3/contact/update/63cb08e978cb16a16a74ba01 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ricky",
    "lastName": "Blomquist",
    "email": "rblomquist@test.com",
    "favoriteColor": "Red",
    "birthday": "07/19/1992"
}

###

DELETE http://localhost:8080/week3/contact/delete/63cb058ba3e73632fc780cef

