# Week 2 requets
GET http://localhost:8080/contact

###

GET http://localhost:8080/contact/63bc6bedc21a515bbcc0137f

###

GET http://localhost:8080/contact/63bc6bedc21a515bbcc01380

###
GET http://localhost:8080/contact/63bc6bedc21a515bbcc01381



###
GET https://cse341-6rfr.onrender.com/contact

###

GET https://cse341-6rfr.onrender.com/contact/63bc6bedc21a515bbcc0137f

###

GET https://cse341-6rfr.onrender.com/contact/63bc6bedc21a515bbcc01380

###
GET https://cse341-6rfr.onrender.com/contact/63bc6bedc21a515bbcc01381

# Week 3 requests

###

get http://localhost:8080/contact

###

POST http://localhost:8080/contact/add HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kaya",
    "lastName": "Blomquist",
    "email": "Kaya@gmail.com",
    "favoriteColor": "purple",
    "birthday": "03/12/2021"
}

###

PUT http://localhost:8080/contact/update/63cc165404fdc8f3ee81aece HTTP/1.1
Content-Type: application/json

{
    "firstName": "Juliette",
    "lastName": "Blomquist",
    "email": "Mblomquist@test.com",
    "favoriteColor": "Red",
    "birthday": "05/25/1995"
}

###

DELETE http://localhost:8080/contact/delete/63cc165404fdc8f3ee81aece
